### ISSUE TITLE
Fix the blog posting loop.

### ISSUE THREAD

**Issue by kantrowitz** [thesocompany/thesocompany.github.io#21]
I added it to the navigation, but the link/loop is incorrect. It's currently living in a commit to the add-blog-00 branch. 

Here's the link to the commit:  https://github.com/thesocompany/thesocompany.github.io/commit/733124fa2fbad8fae758521cb6c41582b15ad103

**Comment by dannychapman** [comment]
@kantrowitz Assuming this is set? If so, please feel free to close out.
